import type { Metadata } from "next";
import "./globals.css";
import { Raleway } from "next/font/google";

const openSans = Raleway({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Joshua David",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={openSans.className}>
      <body className="dark">{children}</body>
    </html>
  );
}
